@if ($errors->any())<div class="form-errors" role="alert"><strong>There are a few details to check.</strong><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="form-grid">
    <div class="field full-field"><label for="name">Course name <span>*</span></label><input id="name" name="name" value="{{ old('name', $course->name ?? '') }}" required maxlength="255" placeholder="e.g. Full-stack web development"><small>Use a name students will recognise.</small>@error('name')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field full-field"><label for="description">Description <span>*</span></label><textarea id="description" name="description" rows="4" maxlength="2000" required placeholder="What will students learn in this course?">{{ old('description', $course->description ?? '') }}</textarea><small>Tell students what the course covers (up to 2,000 characters).</small>@error('description')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="duration">Duration <span>*</span></label><div class="input-suffix"><input id="duration" name="duration" type="number" min="1" max="520" step="1" value="{{ old('duration', $course->duration ?? '') }}" required placeholder="12"><span>weeks</span></div>@error('duration')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="fee">Course fee <span>*</span></label><div class="input-prefix"><span>{{ config('app.currency_symbol', 'Rs.') }}</span><input id="fee" name="fee" type="number" min="0" max="99999999.99" step="0.01" value="{{ old('fee', $course->fee ?? '') }}" required placeholder="25000.00"></div><small>Enter the fee in your institute’s local currency.</small>@error('fee')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="difficulty">Difficulty <span>*</span></label><select id="difficulty" name="difficulty" required><option value="">Choose a level</option>@foreach(['Easy', 'Medium', 'Hard'] as $difficulty)<option value="{{ $difficulty }}" @selected(old('difficulty', $course->difficulty ?? '') === $difficulty)>{{ $difficulty }}</option>@endforeach</select>@error('difficulty')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><span class="field-label">Availability</span><label class="toggle-field"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $course->is_active ?? true))><span class="toggle-switch"></span><span><strong>Course is active</strong><small>Visible as currently offered by your institute.</small></span></label>@error('is_active')<span class="field-error">{{ $message }}</span>@enderror</div>
</div>
