@extends('layouts.app')
@section('title', 'Courses')
@section('section', 'Courses')
@section('content')
<div class="page-heading"><div><p class="eyebrow">LEARNING DIRECTORY</p><h1>Courses <span class="heading-count">{{ $courses->total() }}</span></h1><p class="page-lede">Your institute’s course catalogue, all in one place.</p></div><a class="button button-primary" href="{{ route('courses.create') }}"><span>＋</span> Add course</a></div>
<section class="data-panel">
    <div class="panel-toolbar"><div><h2>Course catalogue</h2><p>{{ $courses->total() }} {{ Str::plural('course', $courses->total()) }} in your catalogue</p></div><form class="search-form course-search" method="GET" action="{{ route('courses.index') }}"><label class="sr-only" for="course-search">Search courses</label><span class="search-icon">⌕</span><input id="course-search" type="search" name="search" value="{{ request('search') }}" placeholder="Search course name"><label class="sr-only" for="difficulty-filter">Filter by difficulty</label><select id="difficulty-filter" name="difficulty"><option value="">All levels</option>@foreach(['Easy', 'Medium', 'Hard'] as $difficulty)<option value="{{ $difficulty }}" @selected(request('difficulty') === $difficulty)>{{ $difficulty }}</option>@endforeach</select><label class="sr-only" for="status-filter">Filter by status</label><select id="status-filter" name="status"><option value="">All status</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select><button type="submit">Filter</button>@if(request()->hasAny(['search', 'difficulty', 'status']))<a class="clear-search" href="{{ route('courses.index') }}">Clear</a>@endif</form></div>
    @if($courses->count())
    <div class="table-wrap"><table class="data-table course-table"><thead><tr><th>COURSE</th><th>DURATION</th><th>FEE</th><th>LEVEL</th><th>STATUS</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>
        @foreach($courses as $course)
        <tr><td><a class="course-cell" href="{{ route('courses.show', $course) }}"><span class="course-icon course-icon-{{ $course->id % 4 }}">{{ ['✳', '◈', '⌘', '✦'][$course->id % 4] }}</span><span><strong>{{ $course->name }}</strong><small>{{ Str::limit($course->description, 70) }}</small></span></a></td><td>{{ $course->duration }} {{ Str::plural('week', $course->duration) }}</td><td>{{ number_format((float) $course->fee, 2) }}</td><td><span class="level-pill level-{{ Str::lower($course->difficulty) }}">{{ $course->difficulty }}</span></td><td><span class="status-pill {{ $course->is_active ? 'is-active' : 'is-inactive' }}"><i></i>{{ $course->is_active ? 'Active' : 'Inactive' }}</span></td><td><div class="row-actions"><a href="{{ route('courses.show', $course) }}" class="icon-action" aria-label="View {{ $course->name }}">↗</a><a href="{{ route('courses.edit', $course) }}" class="icon-action" aria-label="Edit {{ $course->name }}">✎</a><form method="POST" action="{{ route('courses.destroy', $course) }}" data-confirm="Delete the {{ $course->name }} course?" onsubmit="return confirm(this.dataset.confirm)">@csrf @method('DELETE')<button class="icon-action danger-action" aria-label="Delete {{ $course->name }}">⌫</button></form></div></td></tr>
        @endforeach
    </tbody></table></div>
    <div class="pagination-bar"><p>Showing <strong>{{ $courses->firstItem() }}–{{ $courses->lastItem() }}</strong> of <strong>{{ $courses->total() }}</strong> courses</p>{{ $courses->onEachSide(1)->links('vendor.pagination.campus') }}</div>
    @else
    <div class="empty-state"><span class="empty-icon">▤</span><h3>{{ request()->hasAny(['search', 'difficulty', 'status']) ? 'No courses match these filters' : 'Your catalogue is ready to grow' }}</h3><p>{{ request()->hasAny(['search', 'difficulty', 'status']) ? 'Adjust your search or try a different level or status.' : 'Add your first course to share what your institute teaches.' }}</p>@if(request()->hasAny(['search', 'difficulty', 'status']))<a class="button button-secondary" href="{{ route('courses.index') }}">Clear filters</a>@else<a class="button button-primary" href="{{ route('courses.create') }}">＋ Add your first course</a>@endif</div>
    @endif
</section>
@endsection
