@extends('layouts.app')
@section('title', $course->name)
@section('section', 'Courses / Details')
@section('content')
<a href="{{ route('courses.index') }}" class="back-link">← <span>Course catalogue</span></a>
<section class="detail-hero course-detail-hero"><span class="detail-course-icon course-icon-{{ $course->id % 4 }}">{{ ['✳', '◈', '⌘', '✦'][$course->id % 4] }}</span><div><p class="eyebrow">COURSE OVERVIEW · #{{ str_pad((string) $course->id, 4, '0', STR_PAD_LEFT) }}</p><h1>{{ $course->name }}</h1><p class="page-lede">Added {{ $course->created_at->format('F j, Y') }}</p></div><a class="button button-primary" href="{{ route('courses.edit', $course) }}">✎ Edit course</a></section>
<section class="detail-card"><div class="detail-card-heading"><div><p class="eyebrow">COURSE INFORMATION</p><h2>Offering details</h2></div><span class="status-pill {{ $course->is_active ? 'is-active' : 'is-inactive' }}"><i></i>{{ $course->is_active ? 'Active' : 'Inactive' }}</span></div><p class="course-description">{{ $course->description }}</p><dl class="detail-grid course-detail-grid"><div><dt>Duration</dt><dd>{{ $course->duration }} {{ Str::plural('week', $course->duration) }}</dd></div><div><dt>Course fee</dt><dd>{{ config('app.currency_symbol', 'Rs.') }} {{ number_format((float) $course->fee, 2) }}</dd></div><div><dt>Difficulty</dt><dd><span class="level-pill level-{{ Str::lower($course->difficulty) }}">{{ $course->difficulty }}</span></dd></div><div><dt>Availability</dt><dd>{{ $course->is_active ? 'Currently offered' : 'Not currently offered' }}</dd></div></dl></section>
<div class="detail-footer"><span>Last updated {{ $course->updated_at->diffForHumans() }}</span><form method="POST" action="{{ route('courses.destroy', $course) }}" data-confirm="Delete the {{ $course->name }} course?" onsubmit="return confirm(this.dataset.confirm)">@csrf @method('DELETE')<button class="button button-danger-quiet" type="submit">Delete course</button></form></div>
@endsection
